### ISSUE TITLE
Still broken for pg10+ version

### ISSUE THREAD

**Issue by rjuju** [rjuju/postgres-manage#3]
Sorry, my review for latest commits wasn't thorough enough, there are still problems:

```
$ pg 10.dev
Version bizarre 10.dev dans majeur_mineur
[...]

$ pg dev
$ echo $PGDATA
/home/rjuju/postgres/pgs/postgresql-HEAD../data
$ pgls
  Instance     Port Esclave?
-----------------------------
* HEAD../0     8653 Non
[..]
```
but
A quick fix for first issue could be

```diff
diff --git a/postgres.pl b/postgres.pl
index e37b22f..3fb73b3 100755
--- a/postgres.pl
+++ b/postgres.pl
@@ -142,7 +142,7 @@ sub majeur_mineur
     }
     else
     {
-        $version =~ /^(\d+)\.(\d+)$/
+        $version =~ /^(\d+)\.(\w+)$/
        or croak "Version bizarre $version dans majeur_mineur\n";
    return ($1,0,$2);
     }
```

(or maybe something more discriminant if needed, but env() should take care of filtering any garbage), but then you end up with a 3 digits version, which breaks compatibility with previous handling of pg10+:

```
$ env|ag PGDATA
PGDATA=/home/rjuju/postgres/pgs/postgresql-10.0.dev/data
```

(while I previously had:
```
$ pgls
-----------------------------
* 10.dev/0    12205 Non
[...]
```
)

which relies on 10.0.X being an alias for 10.X, ie. if 3 digits are passed to majeur_mineur() it's computed as-is without any check, while not truly being an alias:

```
$ pg 10.0.0
$ echo $?
0
$ echo $PGPORT
6891
$ pg 10.0
$ echo $?
0
$ echo $PGPORT
17995
```

I think that relying on 10.0.X being an alias to 10.X will cause more pain than benefits.  Probably it's time to do a big refactoring of the version handling, revert latest commits and implement pg10 compatibility in a more robust way (more like what was previously done).

@marco44 any thoughts on this?

**Comment by marco44** [comment]
If you have some time, go for it :)

**Comment by rjuju** [comment]
I think I fixed all pg10+ issues long ago, so I'm closing it.
