### ISSUE TITLE
manage --with-feature compatibility with versions

### ISSUE THREAD

**Issue by marco44** [rjuju/postgres-manage#8]
With 11 coming, --with-llvm will be available. But it's only avaialble starting on this version. Maybe it's time we add an array of flags with compatible versions (and we use it to cleanup the CONFIGOPTS on the fly ?

**Comment by rjuju** [comment]
+1.  It'd also be nice to find a way to cleanup the option passed when starting postgres (see start_one_cluster).

**Comment by marco44** [comment]
Yup. One thing seems weird though… the other hash uses "HEAD." as a key... does this work ? (it seems weird to me)
